# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghostboard
      MONGO_INITDB_ROOT_PASSWORD: jP5yF6mN5rA6lU7hI1eD5wV5lE8lT3zZ
    volumes:
    - ghostboard-db:/data/db

volumes:
  ghostboard-db:
    external: true